POST http://localhost:8008/register
Content-Type: application/json

{
    "name": "william2",
    "email": "willia2m@gmail.com",
    "password": "1234abcd"
}


###

POST http://localhost:8008/login
Content-Type: application/json

{
    "email": "bill@gmail.com",
    "password": "123abc"
}


###

GET http://localhost:8008/posts
Content-Type: application/json

{
    "current_post_id": 19,
    "get_next": 4
}


###
POST http://localhost:8008/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YmlsbEBnbWFpbC5jb20.zAKrxkilSaW8ZjtLNP0w89S1Kv_AbF6zeIwW9pGr6UY
Content-Type: application/json

{
    "title": "post number 4",
    "description": "this is a post the fourth one",
    "photos": [
        {
            "url": "image1.com"
        },
        {
            "url": "image2.com"
        },
        {
            "url": "image3.com"
        },
        {
            "url": "image4.com"
        },
        {
            "url": "image5.com"
        }
    ]
}

###

POST http://localhost:8008/posts/edit/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YmlsbEBnbWFpbC5jb20.zAKrxkilSaW8ZjtLNP0w89S1Kv_AbF6zeIwW9pGr6UY
Content-Type: application/json

{
    "title": "post number 4 edited",
    "description": "this is a post the fourth one",
    "post_id": 19
}

###
POST http://localhost:8008/posts/comment/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YmlsbEBnbWFpbC5jb20.zAKrxkilSaW8ZjtLNP0w89S1Kv_AbF6zeIwW9pGr6UY
Content-Type: application/json

{
    "content": "comment on post 4 by billyuan",
    "post_id": 19
}




